---
- name: install unzip
  apt:
    name: unzip
    state: installed

- name: download and unzip mautic
  unarchive:
    src: "https://github.com/mautic/mautic/archive/{{ mautic_version }}.zip"
    dest: "/opt"
    remote_src: yes
    owner: "{{ mautic_user }}"
    group: "{{ mautic_group }}"
    creates: "/opt/mautic-{{ mautic_version }}"

- name: copy mautic into directory
  synchronize:
    src: "/opt/mautic-{{ mautic_version }}/"
    dest: "{{ mautic_destination }}"
  delegate_to: "{{ inventory_hostname }}"

- name: composer install
  become: no
  command: "composer install"
  args:
    chdir: "{{ mautic_destination }}"
    creates: "{{ mautic_destination }}/vendor/autoload.php"
